CREATE TYPE "AdminRole" AS ENUM ('SUPER_ADMIN', 'ADMIN');

ALTER TABLE "Admin"
  ADD COLUMN "role" "AdminRole" NOT NULL DEFAULT 'SUPER_ADMIN',
  ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Admin" ALTER COLUMN "role" SET DEFAULT 'ADMIN';
